@startuml casa_musica

class Sala {
    idSala: int
    nomeSala: string
}

class Sector {
    idSector: int
    nomeSector: string
    idSala: int
}

class Lugar {
    idLugar: int
    numero: int
    idSector: int
}

class Espectaculo {
    idEspectaculo: int
    nome: string
    descricao: string
    diaHora: DateTime
    duracao: int
    precoBase: double
}

class Artista {
    idArtista: int
    nome: string
    nacionalidade: string
    biografia: string
}

class ProgramacaoCultural {
    idProgramacao: int
    idEspectaculo: int
    idArtista: int
    dataHoraLimiteReserva: DateTime
}

class Cliente {
    idCliente: int
    nome: string
    nacionalidade: string
    morada: string
    email: string
}

class Bilhete {
    idBilhete: int
    idCliente: int
    idEspectaculo: int
    idLugar: int
    dataHoraReserva: DateTime
    dataHoraLimiteAquisicao: DateTime
    precoTotal: double
}

class Estatisticas {
    idEstatisticas: int
    idEspectaculo: int
    publico: int
    receitasObtidas: double
}

Sala "1" -- "*" Sector : idSala
Sector "1" -- "*" Lugar : idSector 
Espectaculo "*" -- "*" Artista 
Cliente "1" -- "*" Bilhete 
Espectaculo "1" -- "*" Bilhete  
ProgramacaoCultural "1" -- "1" Espectaculo  
ProgramacaoCultural "1" -- "1" Artista  

Bilhete "1" -- "*" Lugares : idLugar 

@enduml
