import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';

class WaterActivity {
  late String id; // ID generated by Firestore

  late String name;
  late String description;
  late double waterFlow;

  WaterActivity({
    required this.name,
    required this.description,
    required this.waterFlow,
  });

  // Convert WaterActivity object to a Map
  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'description': description,
      'waterFlow': waterFlow,
    };
  }

  // Create WaterActivity object from a Map
  factory WaterActivity.fromMap(String id, Map<String, dynamic> map) {
    return WaterActivity(
      name: map['name'],
      description: map['description'],
      waterFlow: map['waterFlow'],
    )..id = id;
  }
}


class WateractivityService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Future<bool> addWaterActivity(String userId, WaterActivity waterActivity) async {
    try {
      await _firestore.collection('water_activities').add(waterActivity.toMap());
      return true;
    } catch (e) {
      print("Error adding water consumption: $e");
      return false;
    }
  }
}