@startuml


frame "Deployment View" {

  node "Firebase Server Machine" as firebase{
    database "Firestore Database" as firebasedb
    artifact "Firebase authentication" as firebaseauth
  }


  node "Mobile Device" as smartphone{
    artifact "WaterXPTO Application (Flutter)" as gui
    artifact "WaterXPTO Logic Service (Flutter)" as logic
    database "Local Storage" as local
  }
}


smartphone -- firebase
gui -[dashed]-|> logic
logic -[dashed]-|>local
logic -[dashed]-|>firebasedb
logic -[dashed]-|>firebaseauth

firebasedb -[hidden]- firebaseauth

@enduml