class User {
    -String : name;
    -Date : birthDate;
    -String : email;
    -String : password;
    -Nacionality : nationality;
    -Region : region;

}
note left : nationality and region are enums

class Goal {
    -String : name;
    -String : description;
    -Date : deadline;
}


class WaterConsumption {
    -Date : finishDate;
    -Double : duration;
}


class WaterActivity {

    -String : name;
    -String : description;
    -Double : waterFlow; 

}


class Tip {
    
    -String : name;
    -String : description;

}

User "*" -left- "1" WaterActivity 

(User, WaterActivity) .. WaterConsumption

User "1" --> "*" Goal

Tip "*" -- "*" User



