@startuml

frame "Logical View" {
    package "WaterXPTO APPLICATION" {

    package "WaterXPTO Logic" {
        package Statistics {

        }
        
        package WaterTimer {
        

        }

        package GoalSystem {

        }

        package TipSystem {
            
        }


    }

    package GUI {

    }


    package InternalDatabase {

    }


}

package ExeternalServices {
    
    package "Firestore Database" { 
        
    }
    package "Firebase authentication" {

    }

}
}

GUI .down.> "WaterXPTO Logic"

"WaterXPTO Logic" <.right.> "Firestore Database"
"WaterXPTO Logic" <.right.> "Firebase authentication"

"WaterXPTO Logic" .down.> InternalDatabase

@enduml