@startuml

frame "Logical View" {
    package APPLICATION {

    package Logic {
        package Statistics {

        }
        
        package WaterTimer {
        

        }

        package GoalSystem {

        }

        package TipSystem {
            
        }


    }

    package GUI {

    }


    package InternalDatabase {

    }


}

package ExeternalServices {
    
    package Database { 
        
    }
    package Firebase {

    }

}
}

GUI .down.> Logic

Logic <.right.> Database
Logic <.right.> Firebase

Logic .down.> InternalDatabase

@enduml